#*****************************************************************************************#
#     ____   ____ __         __                __    _________ __                         #
#     \   \_/   /|__|_______/  |_ __ _______  |  |  /   _____/|  |__   ____ ______        #
#      \       / |  \_  __ \   __\  |  \__  \ |  |  \_____  \ |  |  \ /  _ \\  __ \       #
#       \     /  |  ||  | \/|  | |  |  // __ \|  |__/        \|   |  (  |_| )  |_| |      #
#        \___/   |__||__|   |__| |____/(______/____/_________/|___|__/\____/|   __/       #
#                                                                           |__|          #
#     *****************************************************************************       #
#                                                                                         #
#                                 VirtualShop - from Pikod                                #
#                             https://wwww.youtube.com/c/pikod                            #
#                                                                                         #
#                   If you want to remove the lore, delete from config.                   #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

categoryMenuSize: 3 # Size of categories menu (It's should be between 1-6)
shoppingType: MENU # Method of buy/sell items. (It can be MENU or CHAT)